default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk"
    firebase_app_distribution(
        app: "1:716737066244:android:aa2d1d00f2adfefdd50c51",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
        android_artifact_type:"APK",
        android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
        testers:"zahermahmoud80@gmail.com",
#         groups: "qa-team, trusted-testers"
        release_notes:"First Fastlane Firebase Distribution cicd App"
      )
  end
end